apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spiderfoot-data
  namespace: devsec
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: microk8s-hostpath   # MicroK8s default
  resources:
    requests:
      storage: 5Gi
